version: '3.8'

services:
  api_service:
    build: .
    restart: always
    ports:
      - 1991:1991
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/wsd?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: wsd
      MYSQL_USER: nazran
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  springapimysql-net:
